In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Load the dataset

In [ ]:
df = pd.read_csv('Customers_Fakedata.csv')
df.head()

,CustomerID,Name,Age,Gender,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Unnamed,Gender
0,CUST1000,Ali Hassan,72.0,NaN,ali.hassan@gmail.com,123456789.0,837.31,10/12/2023,Books,3.0,NaN,NaN
1,CUST1001,Fatma Ali,NaN,Female,fatma.ali@hotmail.com,NaN,900.25,2/23/2023,NaN,3.0,NaN,Female
2,CUST1002,Ahmed Mahmoud,-1.0,male,ahmed.mahmoud@hotmail.com,NaN,761.72,7/7/2023,Toys,2.0,NaN,male
3,CUST1003,Ahmed Gaber,-1.0,F,ahmed.gaber@gmail.com,NaN,303.72,12/30/2023,NaN,2.0,NaN,F
4,CUST1004,Ali Ibrahim,73.0,M,ali.ibrahim@yahoo.com,987654321.0,635.81,12/7/2023,Clothing,2.0,NaN,M

In [ ]:
print("=== Dataset Shape ===")
print(df.shape)

print("\n=== First 5 Rows ===")
display(df.head())

print("\n=== Dataset Information ===")
df.info()

=== Dataset Shape ===
(2150, 12)

=== First 5 Rows ===

,CustomerID,Name,Age,Gender,Email,Phone,PurchaseAmount,PurchaseDate,ProductCategory,Rating,Unnamed,Gender
0,CUST1000,Ali Hassan,72.0,NaN,ali.hassan@gmail.com,123456789.0,837.31,10/12/2023,Books,3.0,NaN,NaN
1,CUST1001,Fatma Ali,NaN,Female,fatma.ali@hotmail.com,NaN,900.25,2/23/2023,NaN,3.0,NaN,Female
2,CUST1002,Ahmed Mahmoud,-1.0,male,ahmed.mahmoud@hotmail.com,NaN,761.72,7/7/2023,Toys,2.0,NaN,male
3,CUST1003,Ahmed Gaber,-1.0,F,ahmed.gaber@gmail.com,NaN,303.72,12/30/2023,NaN,2.0,NaN,F
4,CUST1004,Ali Ibrahim,73.0,M,ali.ibrahim@yahoo.com,987654321.0,635.81,12/7/2023,Clothing,2.0,NaN,M

=== Dataset Information ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2150 entries, 0 to 2149
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       2150 non-null   object
 1   Name             2150 non-null   object
 2   Age              1630 non-null   float64
 3   Gender           1877 non-null   object
 4   Email            2150 non-null   object
 5   Phone            1072 non-null   float64
 6   PurchaseAmount   2049 non-null   float64
 7   PurchaseDate     2150 non-null   object
 8   ProductCategory  1573 non-null   object
 9   Rating           1821 non-null   float64
 10  Unnamed          0 non-null      float64
 11    Gender         1877 non-null   object
dtypes: float64(5), object(7)
memory usage: 201.7+ KB

In [ ]:
print("=== Column Names ===")

for i, col in enumerate(df.columns):
    print(i, repr(col))

=== Column Names ===
0 'CustomerID'
1 'Name'
2 'Age'
3 'Gender'
4 'Email'
5 'Phone'
6 'PurchaseAmount'
7 'PurchaseDate'
8 'ProductCategory'
9 'Rating'
10 'Unnamed'
11 '  Gender  '

### Missing Values

In [ ]:
print("=== Missing Values Count ===")
print(df.isna().sum())

print("\n=== Missing Values Percentage ===")

missing_percentage = (df.isna().sum() / len(df)) * 100

print(missing_percentage.round(2))

=== Missing Values Count ===
CustomerID            0
Name                  0
Age                 520
Gender              273
Email                 0
Phone              1078
PurchaseAmount      101
PurchaseDate          0
ProductCategory     577
Rating              329
Unnamed            2150
  Gender            273
dtype: int64

=== Missing Values Percentage ===
CustomerID           0.00
Name                 0.00
Age                 24.19
Gender              12.70
Email                0.00
Phone               50.14
PurchaseAmount       4.70
PurchaseDate         0.00
ProductCategory     26.84
Rating              15.30
Unnamed            100.00
  Gender            12.70
dtype: float64

### Duplicate Rows

In [ ]:
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 50

# Data Cleaning

In [ ]:
print("=== Gender Values ===")
print(df['Gender'].value_counts(dropna=False))

=== Gender Values ===
Gender
M         346
Female    314
Male      313
male      303
F         302
female    299
NaN       273
Name: count, dtype: int64

In [ ]:
print("=== Age Statistics ===")
print(df['Age'].describe())

print("\n=== Smallest 10 Ages ===")
print(df['Age'].nsmallest(10))

print("\n=== Largest 10 Ages ===")
print(df['Age'].nlargest(10))

=== Age Statistics ===
count    1630.000000
mean       85.180982
std        86.794111
min        -1.000000
25%        -1.000000
50%        54.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

=== Smallest 10 Ages ===
2    -1.0
3    -1.0
6    -1.0
10   -1.0
11   -1.0
19   -1.0
22   -1.0
25   -1.0
26   -1.0
28   -1.0
Name: Age, dtype: float64

=== Largest 10 Ages ===
7     200.0
9     200.0
16    200.0
17    200.0
24    200.0
32    200.0
33    200.0
34    200.0
35    200.0
40    200.0
Name: Age, dtype: float64

In [ ]:
print("=== Purchase Amount Statistics ===")
print(df['PurchaseAmount'].describe())

print("\n=== Missing Purchase Amount ===")
print(df['PurchaseAmount'].isna().sum())

=== Purchase Amount Statistics ===
count    2049.000000
mean      509.418882
std       288.257697
min         5.060000
25%       263.680000
50%       519.250000
75%       762.910000
max       999.560000
Name: PurchaseAmount, dtype: float64

=== Missing Purchase Amount ===
101

In [ ]:
print("=== Rating Values ===")

print(
    df['Rating']
    .value_counts(dropna=False)
    .sort_index()
)

=== Rating Values ===
Rating
1.0     269
2.0     316
3.0     334
4.0     285
5.0     319
10.0    298
NaN     329
Name: count, dtype: int64

In [ ]:
print("=== Product Category Values ===")

print(
    df['ProductCategory']
    .value_counts(dropna=False)
)

=== Product Category Values ===
ProductCategory
NaN            577
Clothing       332
Electronics    327
Books          311
Home           306
Toys           297
Name: count, dtype: int64

In [ ]:
print("=== Purchase Date Sample ===")
print(df['PurchaseDate'].head(10))

print("\n=== Purchase Date Data Type ===")
print(df['PurchaseDate'].dtype)

=== Purchase Date Sample ===
0    10/12/2023
1     2/23/2023
2      7/7/2023
3    12/30/2023
4     12/7/2023
5     1/16/2025
6     6/12/2024
7     5/17/2024
8    32/13/2020
9     1/24/2025
Name: PurchaseDate, dtype: object

=== Purchase Date Data Type ===
object

In [ ]:
print("=== Removing Unnecessary Columns ===")

columns_to_drop = [
    'Unnamed',
    '  Gender  '
]

df = df.drop(
    columns=[col for col in columns_to_drop if col in df.columns]
)

print("\n=== Remaining Columns ===")
print(df.columns.tolist())

=== Removing Unnecessary Columns ===

=== Remaining Columns ===
['CustomerID', 'Name', 'Age', 'Gender', 'Email', 'Phone', 'PurchaseAmount', 'PurchaseDate', 'ProductCategory', 'Rating']

In [ ]:
print("=== Gender Before Cleaning ===")

print(df['Gender'].value_counts(dropna=False))


df['Gender'] = df['Gender'].str.strip()


df['Gender'] = df['Gender'].str.title()


df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'F': 'Female'
})


print("\n=== Gender After Cleaning ===")

print(df['Gender'].value_counts(dropna=False))

=== Gender Before Cleaning ===
Gender
M         346
Female    314
Male      313
male      303
F         302
female    299
NaN       273
Name: count, dtype: int64

=== Gender After Cleaning ===
Gender
Male      962
Female    915
NaN       273
Name: count, dtype: int64

In [ ]:
print("=== Age Before Cleaning ===")

print(df['Age'].describe())

invalid_age_mask = (
    (df['Age'] < 15) |
    (df['Age'] > 100)
)

print("\n=== Invalid Age Count ===")
print(invalid_age_mask.sum())

df.loc[invalid_age_mask, 'Age'] = np.nan


print("\n=== Missing Age After Cleaning ===")
print(df['Age'].isna().sum())


print("\n=== Age After Cleaning ===")
print(df['Age'].describe())

=== Age Before Cleaning ===
count    1630.000000
mean       85.180982
std        86.794111
min        -1.000000
25%        -1.000000
50%        54.000000
75%       200.000000
max       200.000000
Name: Age, dtype: float64

=== Invalid Age Count ===
1123

=== Missing Age After Cleaning ===
1643

=== Age After Cleaning ===
count    507.000000
mean      54.455621
std       21.529268
min       15.000000
25%       36.000000
50%       55.000000
75%       73.000000
max       90.000000
Name: Age, dtype: float64

In [ ]:
print("=== Rating Before Cleaning ===")

print(df['Rating'].value_counts(dropna=False).sort_index())


invalid_rating_mask = (
    (df['Rating'] < 1) |
    (df['Rating'] > 5)
)

print("\n=== Invalid Rating Count ===")
print(invalid_rating_mask.sum())

df.loc[invalid_rating_mask, 'Rating'] = np.nan

print("\n=== Rating After Cleaning ===")

print(df['Rating'].value_counts(dropna=False).sort_index())

=== Rating Before Cleaning ===
Rating
1.0     269
2.0     316
3.0     334
4.0     285
5.0     319
10.0    298
NaN     329
Name: count, dtype: int64

=== Invalid Rating Count ===
298

=== Rating After Cleaning ===
Rating
1.0    269
2.0    316
3.0    334
4.0    285
5.0    319
NaN    627
Name: count, dtype: int64

In [ ]:
print("=== Purchase Date Before Cleaning ===")

print(df['PurchaseDate'].head(10))

df['PurchaseDate'] = pd.to_datetime(
    df['PurchaseDate'],
    format='%m/%d/%Y',
    errors='coerce'
)


print("\n=== Invalid Purchase Dates ===")

print(df['PurchaseDate'].isna().sum())


print("\n=== Purchase Date Data Type ===")

print(df['PurchaseDate'].dtype)

=== Purchase Date Before Cleaning ===
0    10/12/2023
1     2/23/2023
2      7/7/2023
3    12/30/2023
4     12/7/2023
5     1/16/2025
6     6/12/2024
7     5/17/2024
8    32/13/2020
9     1/24/2025
Name: PurchaseDate, dtype: object

=== Invalid Purchase Dates ===
122

=== Purchase Date Data Type ===
datetime64[ns]

## Handle  Missing Values

In [ ]:
print("=== Handling Categorical Missing Values ===")

df['Gender'] = df['Gender'].fillna('Unknown')

df['ProductCategory'] = df['ProductCategory'].fillna('Unknown')

df['Phone'] = df['Phone'].fillna('Unknown')


print("\n=== Missing Values After Categorical Cleaning ===")

print(df[['Gender', 'ProductCategory', 'Phone']].isna().sum())

=== Handling Categorical Missing Values ===

=== Missing Values After Categorical Cleaning ===
Gender             0
ProductCategory    0
Phone              0
dtype: int64

### Handle Duplicates

In [ ]:
print("=== Duplicate Rows Before Removal ===")

duplicate_count = df.duplicated().sum()

print(duplicate_count)


df = df.drop_duplicates()


print("\n=== Duplicate Rows After Removal ===")

print(df.duplicated().sum())

=== Duplicate Rows Before Removal ===
50

=== Duplicate Rows After Removal ===
0

### Final Validation

In [ ]:
print("=== FINAL DATA QUALITY CHECK ===")


print("\nDataset Shape:")
print(df.shape)


print("\nMissing Values:")
print(df.isna().sum())


print("\nMissing Values Percentage:")
print(
    ((df.isna().sum() / len(df)) * 100)
    .round(2)
)


print("\nDuplicate Rows:")
print(df.duplicated().sum())


print("\nData Types:")
print(df.dtypes)

=== FINAL DATA QUALITY CHECK ===

Dataset Shape:
(2100, 10)

Missing Values:
CustomerID            0
Name                  0
Age                1605
Gender                0
Email                 0
Phone                 0
PurchaseAmount       97
PurchaseDate        118
ProductCategory       0
Rating              613
dtype: int64

Missing Values Percentage:
CustomerID          0.00
Name                0.00
Age                76.43
Gender              0.00
Email               0.00
Phone               0.00
PurchaseAmount      4.62
PurchaseDate        5.62
ProductCategory     0.00
Rating             29.19
dtype: float64

Duplicate Rows:
0

Data Types:
CustomerID                 object
Name                       object
Age                       float64
Gender                     object
Email                      object
Phone                      object
PurchaseAmount            float64
PurchaseDate       datetime64[ns]
ProductCategory            object
Rating                    float64
dtype: object

### Save  Clean Dataset

In [ ]:
df.to_csv(
    'Customers_Cleaned.csv',
    index=False
)

print("=== Cleaning Completed Successfully ===")
print("Saved file: Customers_Cleaned.csv")

=== Cleaning Completed Successfully ===
Saved file: Customers_Cleaned.csv

## Customer Analysis

In [ ]:
print(f"Total Customers: {df['CustomerID'].nunique()}")

print("\n=== Gender Distribution ===")
print(df['Gender'].value_counts())

print("\n=== Age Statistics ===")
print(df['Age'].describe())

Total Customers: 2100

=== Gender Distribution ===
Gender
Male       942
Female     891
Unknown    267
Name: count, dtype: int64

=== Age Statistics ===
count    495.000000
mean      54.371717
std       21.591515
min       15.000000
25%       36.000000
50%       55.000000
75%       73.000000
max       90.000000
Name: Age, dtype: float64

Purchase Analysis

In [ ]:
print(f"Total Sales: {df['PurchaseAmount'].sum():,.2f}")

print(f"Average Purchase Amount: {df['PurchaseAmount'].mean():,.2f}")

print(f"Median Purchase Amount: {df['PurchaseAmount'].median():,.2f}")

print(f"Minimum Purchase Amount: {df['PurchaseAmount'].min():,.2f}")

print(f"Maximum Purchase Amount: {df['PurchaseAmount'].max():,.2f}")

Total Sales: 1,021,324.45
Average Purchase Amount: 509.90
Median Purchase Amount: 519.42
Minimum Purchase Amount: 5.06
Maximum Purchase Amount: 999.56

Product Category Analysis

In [ ]:
category_analysis = df.groupby('ProductCategory').agg(
    Total_Sales=('PurchaseAmount', 'sum'),
    Purchase_Count=('PurchaseAmount', 'count'),
    Average_Purchase=('PurchaseAmount', 'mean')
).sort_values(
    by='Total_Sales',
    ascending=False
)

print(category_analysis)

                 Total_Sales  Purchase_Count  Average_Purchase
ProductCategory
Unknown            267729.35             539        496.714935
Clothing           163864.98             305        537.262230
Electronics        154691.51             309        500.619773
Books              150083.23             294        510.487177
Home               143571.07             287        500.247631
Toys               141384.31             269        525.592230

Rating Analysis

In [ ]:
print(f"Average Rating: {df['Rating'].mean():.2f}")

print("\n=== Rating Distribution ===")
print(df['Rating'].value_counts().sort_index())

Average Rating: 3.03

=== Rating Distribution ===
Rating
1.0    266
2.0    310
3.0    326
4.0    278
5.0    307
Name: count, dtype: int64

Sales by Time

In [ ]:
print(f"First Purchase Date: {df['PurchaseDate'].min()}")
print(f"Last Purchase Date: {df['PurchaseDate'].max()}")

yearly_sales = df.groupby(
    df['PurchaseDate'].dt.year
)['PurchaseAmount'].sum()

print("\n=== Sales by Year ===")
print(yearly_sales)

First Purchase Date: 2022-10-27 00:00:00
Last Purchase Date: 2025-07-23 00:00:00

=== Sales by Year ===
PurchaseDate
2022.0     67445.27
2023.0    342414.99
2024.0    363621.93
2025.0    190226.60
Name: PurchaseAmount, dtype: float64